### ISSUE TITLE
모바일 사이드바 영역이 터치를 잡아먹는 버그

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/ttl_front#21]
![image](https://user-images.githubusercontent.com/55120738/152704848-e052aff3-1f85-4c14-8563-5609c6e83d29.png)

색 어둡게 해놓은 부분이 사이드바 부분인데
저기가 터치가 사이드바에 먹혀서 터치가 안되네요
ㅠㅠ 모바일 전체 페이지가 다 그럽니다 수정 부탁...

**Comment by cychann** [comment]
무슨 짓을 해놓은거지 빨리 수정할게욤
