### ISSUE TITLE
사이드바 위치 고정

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/ttl_front#23]
![image](https://user-images.githubusercontent.com/55120738/152874437-35634c62-3dc6-465d-87e6-c397b229192a.png)
![image](https://user-images.githubusercontent.com/55120738/152874441-dca500d9-07e4-4a7e-b0ac-d1973d407351.png)

어느 쪽 컴포넌트가 건드리는지는 모르겠으나.. 피드위치쪽으로 맞춰봅시당..

**Comment by soyekwon** [comment]
마자 이거 위치 달라지는데 ... 왜 그러는지 모르게써여 
제일 상위 컴포넌트 크기를 맞춰야하나 ??

**Comment by cychann** [comment]
앗 고쳐보겠습니당

**Comment by cychann** [comment]
지금 코드를 건드려 봤는데 
이게 스크롤바가 생성이 되어 있으면 sticky 속성이 잘 먹혀서 사이드바 위치가 원래대로 보이고 스크롤바가 없으면 sticky 속성이 안먹히는 것 같아요 @minjj0905  @soyekwon

**Comment by minjj0905** [comment]
오..호... 그럼 어떻게 고쳐지나용

**Comment by soyekwon** [comment]
ㅠㅠㅠ...

**Comment by cychann** [comment]
글 작성 페이지 PR 올리고 나서 해결해보도록 할게욤

**Comment by cychann** [comment]
이 이슈 관련된거 어떻게 해결해야할지 해결방안을 생각해봤는데, 내일 회의 때 같이 얘기해서 결정해봅시다
@minjj0905 @soyekwon

**Comment by soyekwon** [comment]
네

**Comment by minjj0905** [comment]
이 issue는 메인페이지에서만 사이드바를 렌더링 하는 것으로 종결되었습니다.
