### ISSUE TITLE
상단 nav 로그인 여부에 따른 아이템 수정 및 드롭다운 트리거 수정

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/ttl_front#24]
![image](https://user-images.githubusercontent.com/55120738/153115656-44c168b8-d6e6-4d43-ab15-2218157cecd0.png)

로그인 / 회원가입 버튼 추가해야 합니당. (시작하기? 버튼 하나로 퉁쳐도 되고 로그인/회원가입 이런식으로 버튼 하나로 놔둬도 괜찮을듯. 버튼 두개 만들어서 따로해도 괜찮구요)

![image](https://user-images.githubusercontent.com/55120738/153115701-ccae376c-9586-4be1-8ea1-0f34d51d76a8.png)

드롭다운 트리거 유저 이미지 아이콘까지 되도록 수정 please...

**Comment by cychann** [comment]
알겠습니당 :)
