### ISSUE TITLE
글 개수가 맞지 않을 때 ui 깨짐현상

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/ttl_front#34]
![image](https://user-images.githubusercontent.com/55120738/153719844-c34c0a8f-26c0-4c12-b8b9-86248f42121d.png)
![image](https://user-images.githubusercontent.com/55120738/153719867-fe72ea68-59ad-4593-a4bb-3d2beaa98050.png)

사이드바도.. 같이.. 움직이는..
이거 일단 사이드바부터 고정시키고 그다음에 해결해야할듯

**Comment by minjj0905** [comment]
예상되는 상황 : 한명이 유일하게 쓴 태그에 대해 검색을 한다거나... ?

**Comment by minjj0905** [comment]
![image](https://user-images.githubusercontent.com/55120738/153721598-d145e4f6-d4b4-443f-a288-c9381ff91f77.png)
가운데 정렬이 맞나..? 먼가 어색하네요 ㅋㅋ ㅠㅠ

**Comment by cychann** [comment]
음 이거 정렬을 가운데가 아니라 왼쪽으로 해봐야겠네요
고쳐보겠습니당
