### ISSUE TITLE
bug: [mobile] top nav바가 화면 이탈

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/ttl_front#82]

**Comment by minjj0905** [comment]
![image](https://user-images.githubusercontent.com/55120738/154717860-23257ed3-a15e-4eb9-9326-c6d1b9867a2a.png)
스크롤 내려가면 이런식으로 위로 이탈하거나

![image](https://user-images.githubusercontent.com/55120738/154717943-32de376e-60cd-4037-94f1-2e7010113871.png)
페이지 이동하다가 살짝 확대?돼서 아이콘이 짤림

**Comment by cychann** [comment]
버그 찾아주셔서 감사합니다... 고쳐 올게염 🙏
